package com.example.mycafo

import android.annotation.SuppressLint
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.drawable.BitmapDrawable
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.provider.MediaStore
import android.widget.Button
import android.widget.EditText
import android.widget.ImageView
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.ktx.Firebase
import com.google.firebase.storage.FirebaseStorage
import com.google.firebase.storage.ktx.storage
import java.io.ByteArrayOutputStream

class TambahMeja : AppCompatActivity() {

    private lateinit var et_nama_meja: EditText
    private lateinit var et_deskripsi_meja: EditText
    private lateinit var btn_kirim: Button


    // Firebase Firestore
    private lateinit var db: FirebaseFirestore

    @SuppressLint("MissingInflatedId")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_tambah_meja)
        supportActionBar?.hide()

        // Inisialisasi Firestore
        db = FirebaseFirestore.getInstance()


        et_nama_meja = findViewById(R.id.et_nama_meja)
        et_deskripsi_meja= findViewById(R.id.et_deskripsi_meja)
        btn_kirim = findViewById(R.id.btn_kirim)



        btn_kirim.setOnClickListener {
            saveData()
        }

    }
    private fun saveData() {
        val meja = hashMapOf(
            "nama_meja" to et_nama_meja.text.toString(),
            "deskripsi" to et_deskripsi_meja.text.toString(),


        )

        db.collection("meja")
            .add(meja)
            .addOnSuccessListener { documentReference ->
                val idMeja = documentReference.id // Get the AUTO-ID generated by Firestore
                // Add the AUTO-ID to the menu document
                db.collection("meja")
                    .document(idMeja)
                    .update("id", idMeja)
                    .addOnSuccessListener {
                        Toast.makeText(this, "Data Berhasil Disimpan", Toast.LENGTH_SHORT).show()
                        finish()
                    }
                    .addOnFailureListener { e ->
                        Toast.makeText(this, "Gagal memperbarui data", Toast.LENGTH_SHORT).show()
                    }
            }
            .addOnFailureListener { e ->
                Toast.makeText(this, "Data Gagal Disimpan", Toast.LENGTH_SHORT).show()
            }
    }







    }



